[package]
name = "ls-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Append-only encrypted log storage for localsecrets."

[dependencies]
ls-core.workspace = true
ls-json.workspace = true
ls-log.workspace = true
subtle.workspace = true

[lints]
workspace = true
