[package]
name = "ls-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "localsecrets command line client."

[[bin]]
name = "lsec"
path = "src/main.rs"

[dependencies]
ls-http.workspace = true
ls-json.workspace = true

[dev-dependencies]
ls-server.workspace = true

[lints]
workspace = true
